point_zlhr:
  label: Stützpunkte
  printable: true
  featureType: zlhr
  maxResults: 5000
  minScale: 200000
  geometrylessfeatureBtn: true
  refreshFeaturesAfterSave:
    - alldata_zlhr
    - obstacle_zlhr
    - curvesegmaxheightedit_zlhr
  refreshLayersAfterFeatureSave:
    - 47
  copy:
    enable: true
    default: null
    style:
      label: 'Dupliziertes Hindernis'
      fillColor: '#ff0000'
      fillOpacity: 1
      strokeWidth: 4
      strokeColor: '#660033'
  allowLocate: false
  allowDigitize: true
  allowEditData: true
  allowDelete: false
  allowChangeVisibility: false
  allowCustomerStyle: false
  showVisibilityNavigation: false
  allowDeleteByCancelNewGeometry: true
  events:
    onAfterSave: '$sr = http_get("http://localhost:8983/solr/zlhr/dataimport?command=full-import&clean=true&commit=true");'
  toolset:
    -
      type: selectFeature
    -
      type: drawPoint
    -
      type: moveFeature
    -
      type: removeSelected
  useContextMenu: true
  displayPermanent: false
  displayOnInactive: false
  zoomScaleDenominator: 1000
  displayOnSelect: true
  inlineSearch: true
  searchType: currentExtent
  showExtendSearchSwitch: true
  popup:
    title: 'Stützpunkt Anlegen / Bearbeiten'
    width: 850
    height: 740
    remoteData: true
  oneInstanceEdit: true
  view:
    type: table
    settings:
      info: true
      processing: false
      ordering: true
      paging: true
      selectable: false
      autoWidth: false
      order:
        -
          - 0
          - asc
  tableFields:
    point_id:
      label: PunktID
    obstacle_id:
      label: HindernisID
    vertex_name:
      label: Name
  styles:
    default:
      strokeWidth: 1
      fillColor: '#FF0000'
      strokeColor: '#b30000'
      fillOpacity: 0.7
      pointRadius: 10
      label: '${point_id} (${obstacle_id})'
      labelOutlineColor: '#ffcccc'
    select:
      strokeWidth: 3
      fillColor: '#e60000'
      strokeColor: '#330000'
      fillOpacity: 1
      pointRadius: 12
      label: '${point_id} (${obstacle_id})'
      labelOutlineColor: '#ffffff'
  formItems:
    -
      type: tabs
      children:
        -
          type: form
          title: 'Verpflichtende Daten'
          css:
            font-size: 12px
            margin-bottom: 10px
          children:
            -
              type: fieldSet
              children:
                -
                  type: text
                  title: Stützpunkt-ID
                  name: point_id
                  text: 'data.point_id || "wird automatisch vergeben"'
                  mandatory: true
                  css: { width: 25% }
                -
                  type: input
                  title: '(30a) Fortlaufende Nummer des Stützpunktes'
                  name: vertex_number
                  value: 1
                  mandatory: true
                  css: { width: 25% }
                -
                  type: input
                  title: '(9) (Maximale) Hindernishöhe über Meeresniveau (Meter)'
                  name: elevation_top
                  mandatory: true
                  css: { width: 25% }
                  keyup: "console.log(\"keyup on (9)\");\nvar field9 = el;\nvar form = field9.closest(\".modal-body\");\nvar field31 = form.find(\"[name='elevation_base']\");\nvar field10 = form.find(\"[name='height']\");\nif (field31.val() != '') {\n  var height_result = parseFloat(field9.val()) - parseFloat(field31.val())\n  console.log(\"height_result=\" + height_result);\n  if ( ! isNaN(height_result) ) {\n    field10.val(height_result);\n  } else {\n    field10.val('');\n  }\n}\n"
                -
                  type: select
                  title: 'Zugeordnetes Luftfahrthindernis'
                  name: obstacle_id
                  connection: zlhr
                  sql: 'SELECT obstacle_id, obstacle_id || '': '' || name_location FROM data.obstacle order by obstacle_id;'
                  mandatory: true
                  css: { width: 25% }
            -
              type: fieldSet
              children:
                -
                  type: text
                  title: TitelBreite
                  text: '"TextBreite"'
                -
                  type: input
                  title: '(10) Hindernishöhe über Grund (Meter)'
                  name: height
                  mandatory: true
                  css: { width: 33% }
                  keyup: "console.log(\"keyup on (10)\");\nvar field10 = el;\nvar form = field10.closest(\".modal-body\");\nvar field31 = form.find(\"[name='elevation_base']\");\nvar field9 = form.find(\"[name='elevation_top']\");\nif (field31.val() != '') {\n  var height_result = parseFloat(field31.val()) + parseFloat(field10.val())\n  console.log(\"height_result=\" + height_result);\n  if ( ! isNaN(height_result) ) {\n    field9.val(height_result);\n  } else {\n    field9.val('');\n  }\n}\n"
            -
              type: fieldSet
              children:
                -
                  type: text
                  title: TitelLaenge
                  text: '"TextLaenge"'
                -
                  type: input
                  title: '(31) Fußpunkthöhe über Meeresniveau (Meter)'
                  name: elevation_base
                  automatic_detection: true
                  mandatory: true
                  css: { width: 33% }
            -
              type: fieldSet
              children:
                -
                  type: input
                  title: '(12/13) Messgenauigkeit der Lagekoordinaten (Konfidenzintervall 90%)'
                  name: horizontal_convidence_interval_90
                  mandatory: true
                  css: { width: 25% }
                -
                  type: input
                  title: '(12/13) Messgenauigkeit der Lagekoordinaten (Konfidenzintervall 95%)'
                  name: horizontal_convidence_interval_95
                  mandatory: true
                  css: { width: 25% }
                -
                  type: input
                  title: 'Messgenauigkeit der Höhenangaben (Konfidenzintervall 90%)'
                  name: vertical_convidence_interval_90
                  mandatory: true
                  css: { width: 25% }
                -
                  type: input
                  title: 'Messgenauigkeit der Höhenangaben (Konfidenzintervall 95%)'
                  name: vertical_convidence_interval_95
                  mandatory: true
                  css: { width: 25% }
            -
              type: fieldSet
              children:
                -
                  type: select
                  title: 'Katastralgemeinde: Nummer - Name / Gemeinde / Bezirk (Land)'
                  name: KG_NUMMER
                  mandatory: true
                  connection: zlhr
                  automatic_detection: true
                  sql: 'SELECT cadastral_zoning_number, (cadastral_zoning_number || '' - '' || cadastral_zoning_name || '' / '' || municipality || '' / '' || district || '' ('' || federal_state|| '')'') FROM data.ref_admin_unit order by cadastral_zoning_number asc;'
                  css: { width: 100% }
            -
              type: coordinates
              epsgCodes:
                -
                  - 'EPSG:4326'
                  - 'EPSG:4326'
                -
                  - 'EPSG:3035'
                  - 'EPSG:3035'
                -
                  - 'EPSG:3785'
                  - 'EPSG:3785'
        -
          type: form
          title: 'Optionale Angaben'
          css:
            font-size: 12px
            margin-bottom: 10px
          children:
            -
              type: fieldSet
              children:
                -
                  type: input
                  title: '(30b) Stützpunktname'
                  name: vertex_name
                  css: { width: 33% }
                -
                  type: select
                  title: '(46b) Materialtyp'
                  name: material_type_id
                  infoText: 'Wählen Sie bitte aus der Liste den Materialtyp aus.'
                  connection: zlhr
                  sql: 'SELECT material_type_id, material_type_ger FROM data.ref_material_type WHERE valid = TRUE ORDER by material_type_ger asc;'
                  css: { width: 33% }
                -
                  type: select
                  title: '(4d) Hindernistyp des (Stütz-)Punktes'
                  name: obstacle_type_id
                  infoText: 'Wählen Sie bitte aus der Liste den Hindernistyp des (Stütz-)Punktes aus.'
                  connection: zlhr
                  sql: 'SELECT obstacle_type_id, obstacle_type_ger FROM data.ref_obstacle_type WHERE valid = TRUE order by obstacle_type_ger asc;'
                  css: { width: 33% }
            -
              type: fieldSet
              children:
                -
                  type: checkbox
                  title: '(47) Bewegliches Hindernis'
                  name: mobile
                  css: { width: 50% }
                -
                  type: checkbox
                  title: '(48) Hindernis mit Sollbruchstelle'
                  name: frangible
                  css: { width: 50% }
            -
              type: fieldSet
              children:
                -
                  type: input
                  title: '(11) Geoidundulation'
                  name: geoid_undulation
                  css: { width: 50% }
                -
                  type: select
                  title: '(29a / 29b) Baustatus des Stützpunktes'
                  name: construction_status_id
                  connection: zlhr
                  sql: 'SELECT construction_status_id, construction_status_ger FROM data.ref_construction_status WHERE valid = TRUE order by construction_status_id asc;'
                  mandatoryText: 'Bitte geben Sie den Stützpunkt-Status des Hindernisses an.'
                  css: { width: 50% }
            -
              type: fieldSet
              children:
                -
                  type: textArea
                  title: '(33b) Anmerkung'
                  name: remark
                  rows: 2
                  placeholder: 'Hier können Sie Anmerkungen eingeben.'
                  css: { width: 100% }
            -
              type: breakLine
            -
              type: label
              title: 'Hindernisbefeuerung & Tageskennzeichnung (Tkz.)'
            -
              type: fieldSet
              children:
                -
                  type: select
                  title: '(19a) Hindernisbefeuerung'
                  name: lighting_id
                  connection: zlhr
                  sql: 'SELECT lighting_id, lighting_ger FROM data.ref_lighting where valid = TRUE;'
                  css: { width: 25% }
                -
                  type: select
                  title: '(21d) Ausführung der Tkz.'
                  name: marking_pattern_id
                  connection: zlhr
                  sql: 'SELECT marking_pattern_id, marking_pattern_ger FROM data.ref_marking_pattern where valid = TRUE;'
                  css: { width: 25% }
                -
                  type: select
                  title: '(21f) Erste Farbe der Tkz.'
                  name: colour1_marking_colour_id
                  connection: zlhr
                  sql: 'SELECT marking_colour_id, colour_ger FROM data.ref_marking_colour WHERE valid = TRUE;'
                  css: { width: 25% }
                -
                  type: select
                  title: '(21h) Zweite Farbe der Tkz.'
                  name: colour2_marking_colour_id
                  connection: zlhr
                  sql: 'SELECT marking_colour_id, colour_ger FROM data.ref_marking_colour WHERE valid = TRUE;'
                  css: { width: 25% }
            -
              type: breakLine
            -
              type: label
              title: 'Informationen des Ziviltechnikers'
            -
              type: fieldSet
              children:
                -
                  type: input
                  title: '(12) Messgenauigkeit der Lagekoordinaten (Mittlere Fehler)'
                  name: horizontal_mean_error
                  css: { width: 33% }
                -
                  type: select
                  title: '(16) Einheit der Lagekoordinatengenauigkeit'
                  name: horizontal_error_unit_id
                  connection: zlhr
                  sql: 'SELECT unit_id, unit_name FROM data.ref_unit WHERE valid = TRUE ORDER BY unit_id'
                  value: 1
                  css: { width: 33% }
                -
                  type: select
                  title: '(M17a) Erfassungsmethode für Lagekoordinaten'
                  name: horizontal_method_of_observation_id
                  connection: zlhr
                  sql: 'SELECT method_of_observation_id, method_of_observation_ger FROM data.ref_method_of_observation WHERE valid_horizontal = TRUE order by method_of_observation_ger asc;'
                  css: { width: 33% }
            -
              type: fieldSet
              children:
                -
                  type: input
                  title: '(14) Messgenauigkeit der Höhenangaben (Mittlere Fehler)'
                  name: vertical_mean_error
                  css: { width: 33% }
                -
                  type: select
                  title: '(18) Einheit der Höhengenauigkeit'
                  name: vertical_error_unit_id
                  connection: zlhr
                  sql: 'SELECT unit_id, unit_name FROM data.ref_unit WHERE valid = TRUE ORDER BY unit_id'
                  value: 1
                  css: { width: 33% }
                -
                  type: select
                  title: '(M17b) Erfassungsmethode für Höhenangaben'
                  name: vertical_method_of_observation_id
                  connection: zlhr
                  sql: 'SELECT method_of_observation_id, method_of_observation_ger FROM data.ref_method_of_observation WHERE valid_vertical = TRUE order by method_of_observation_ger asc;'
                  css: { width: 33% }
